/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import DataAccessLayer.MayInDAL;
import DataTranferObject.CongThuc;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HuyLV
 */
public class frmCongThuc extends javax.swing.JFrame {

    /**
     * Creates new form frmCongThuc
     */
    public frmCongThuc() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public frmCongThuc(String maMayIn, int suaTienIn) {//Sửa công thức
        initComponents();
        this.setLocationRelativeTo(null);
        txtMaMayIn.setText(maMayIn);
        //Sửa công thức tiền in
        if (suaTienIn == 1) {
            cbxTenCongThuc.addItem("Công thức tiền in");
            txtMaCongThuc.setText(Integer.toString(frmKeHoach.congThucTienIn.getMaCongThuc()));
            spSoThanhPhanCon.setValue(frmKeHoach.tblCongThucThanhPhanTienIn.getRowCount());
            DefaultTableModel tb = (DefaultTableModel) tblCongThucThanhPhan.getModel();
            tb.setRowCount(frmKeHoach.tblCongThucThanhPhanTienIn.getRowCount());
            for (int i = 0; i < frmKeHoach.tblCongThucThanhPhanTienIn.getRowCount(); i++) {
                tblCongThucThanhPhan.setValueAt(frmKeHoach.tblCongThucThanhPhanTienIn.getValueAt(i, 0).toString(), i, 0);
                tblCongThucThanhPhan.setValueAt(frmKeHoach.tblCongThucThanhPhanTienIn.getValueAt(i, 1).toString(), i, 1);
                tblCongThucThanhPhan.setValueAt(frmKeHoach.tblCongThucThanhPhanTienIn.getValueAt(i, 2).toString(), i, 2);

            }
        } else { //Sửa công thức tiền thợ
            cbxTenCongThuc.addItem("Công thức tiền thợ");

            txtMaCongThuc.setText(Integer.toString(frmKeHoach.congThucTienTho.getMaCongThuc()));
            spSoThanhPhanCon.setValue(frmKeHoach.tblCongThucThanhPhanTienTho.getRowCount());
            tblCongThucThanhPhan.removeAll();
            DefaultTableModel tb = (DefaultTableModel) tblCongThucThanhPhan.getModel();
            tb.setRowCount(frmKeHoach.tblCongThucThanhPhanTienTho.getRowCount());
            for (int i = 0; i < frmKeHoach.tblCongThucThanhPhanTienTho.getRowCount(); i++) {
                tblCongThucThanhPhan.setValueAt(frmKeHoach.tblCongThucThanhPhanTienTho.getValueAt(i, 0).toString(), i, 0);
                tblCongThucThanhPhan.setValueAt(frmKeHoach.tblCongThucThanhPhanTienTho.getValueAt(i, 1).toString(), i, 1);
                tblCongThucThanhPhan.setValueAt(frmKeHoach.tblCongThucThanhPhanTienTho.getValueAt(i, 2).toString(), i, 2);

            }
        }
    }

    public frmCongThuc(String maMayIn, boolean congThucIn) {//Thêm công thức

        initComponents();
        this.setLocationRelativeTo(null);
        txtMaMayIn.setText(maMayIn);
        if (congThucIn) {
            cbxTenCongThuc.addItem("Công thức tiền in");
        } else {
            cbxTenCongThuc.addItem("Công thức tiền thợ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxTieuChi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtMaCongThuc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxTenCongThuc = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbxLoaiCongThuc = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCongThucThanhPhan = new javax.swing.JTable();
        spSoThanhPhanCon = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        txtMaMayIn = new javax.swing.JTextField();
        btnTaoCongThuc = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCongThuc = new javax.swing.JTextField();
        btnLuuCongThuc = new javax.swing.JButton();

        cbxTieuChi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Số bản phơi", "Số lượt in" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setText("Mã công thức :");

        txtMaCongThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCongThucActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel7.setText("Tên Công Thức :");

        cbxTenCongThuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel8.setText("Loại Công Thức:");

        cbxLoaiCongThuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxLoaiCongThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAX", "MIN" }));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel9.setText("Thành phần con :");

        tblCongThucThanhPhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblCongThucThanhPhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thành phần ", "Hệ Số", "Tiêu Chí"
            }
        ));
        tblCongThucThanhPhan.setRowMargin(5);
        tblCongThucThanhPhan.setRowHeight(25);
        jScrollPane1.setViewportView(tblCongThucThanhPhan);
        if (tblCongThucThanhPhan.getColumnModel().getColumnCount() > 0) {
            tblCongThucThanhPhan.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(cbxTieuChi));
        }

        spSoThanhPhanCon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spSoThanhPhanCon.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spSoThanhPhanCon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spSoThanhPhanConStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel10.setText("Mã Máy In :");

        txtMaMayIn.setEditable(false);
        txtMaMayIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMaMayIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMayInActionPerformed(evt);
            }
        });

        btnTaoCongThuc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTaoCongThuc.setText("Tạo Công Thức");
        btnTaoCongThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoCongThucActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel11.setText("Công thức được tạo :");

        txtCongThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCongThucActionPerformed(evt);
            }
        });

        btnLuuCongThuc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuuCongThuc.setText("Lưu Công Thức");
        btnLuuCongThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuCongThucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxTenCongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaMayIn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxLoaiCongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaCongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spSoThanhPhanCon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnTaoCongThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(btnLuuCongThuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCongThuc)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaMayIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtMaCongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxTenCongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxLoaiCongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spSoThanhPhanCon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTaoCongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuuCongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaCongThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCongThucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCongThucActionPerformed

    private void spSoThanhPhanConStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spSoThanhPhanConStateChanged
        DefaultTableModel tb = (DefaultTableModel) tblCongThucThanhPhan.getModel();
        tb.setRowCount((int) spSoThanhPhanCon.getModel().getValue());
    }//GEN-LAST:event_spSoThanhPhanConStateChanged

    private void txtMaMayInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMayInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMayInActionPerformed

    private void btnLuuCongThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuCongThucActionPerformed
        //Kiểm tra trước khi Lưu 
        if (txtMaCongThuc.getText().equals("")) {
            QLIN.ThongBao("Chưa có mã công thức", "Xòe rồi", 2);
            return;
        }
        if (!txtCongThuc.getText().equals("")) {
            CongThuc congThuc = new CongThuc(Integer.parseInt(txtMaCongThuc.getText()), cbxTenCongThuc.getSelectedItem().toString(), cbxLoaiCongThuc.getSelectedItem().toString(), txtMaMayIn.getText());
            //Gửi về công thức tiền in , bảng công thức .
            if (cbxTenCongThuc.getSelectedItem().toString().equals("Công thức tiền in")) {
                try {
                    frmKeHoach.congThucTienIn = congThuc.clone();
                    frmKeHoach.tblCongThucThanhPhanTienIn.setModel(tblCongThucThanhPhan.getModel());
                    frmKeHoach.txtCtTienIn.setText(txtCongThuc.getText());
                } catch (CloneNotSupportedException ex) {
                    Logger.getLogger(frmCongThuc.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    frmKeHoach.congThucTienTho = congThuc.clone();
                    frmKeHoach.tblCongThucThanhPhanTienTho.setModel(tblCongThucThanhPhan.getModel());
                    frmKeHoach.txtCtTienTho.setText(txtCongThuc.getText());
                } catch (CloneNotSupportedException ex) {
                    Logger.getLogger(frmCongThuc.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            this.dispose();
        } else {
            QLIN.ThongBao("Hãy tạo công thức trước khi lưu !", "Xòe rồi", 2);
        }
    }//GEN-LAST:event_btnLuuCongThucActionPerformed

    private void btnTaoCongThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoCongThucActionPerformed
        int rowCounts = tblCongThucThanhPhan.getRowCount(); // Đếm số dòng của bảng . 
        txtCongThuc.setText("");
        String congThucThanhPhan = "";
        String congThuc = "";
        int i = 0;
        if (cbxLoaiCongThuc.getSelectedItem().toString().equals("MAX")) {
            congThuc = getDataTable(tblCongThucThanhPhan, i, 1) + "*" + getDataTable(tblCongThucThanhPhan, i, 2);
            while (i < rowCounts) {
                while (i < rowCounts - 1 && getDataTable(tblCongThucThanhPhan, i, 0).equals(getDataTable(tblCongThucThanhPhan, i + 1, 0))) {
                    congThucThanhPhan += "+" + getDataTable(tblCongThucThanhPhan, i + 1, 1) + "*" + getDataTable(tblCongThucThanhPhan, i + 1, 2);
                    i++;
                }
                if (i == rowCounts - 1) {
                    congThuc += congThucThanhPhan;
                    i++;

                } else {
                    congThuc += congThucThanhPhan + ",";
                    congThuc += getDataTable(tblCongThucThanhPhan, i + 1, 1) + "*" + getDataTable(tblCongThucThanhPhan, i + 1, 2);
                    congThucThanhPhan = "";
                    i++;
                }
            }
            congThuc = "MAX(" + congThuc + ")";
        } else {
            congThuc = getDataTable(tblCongThucThanhPhan, 0, 1) + "*" + getDataTable(tblCongThucThanhPhan, 0, 2);
            while (i < rowCounts) {
                while (i < rowCounts - 1 && getDataTable(tblCongThucThanhPhan, i, 0).equals(getDataTable(tblCongThucThanhPhan, i + 1, 0))) {
                    congThucThanhPhan += "+" + getDataTable(tblCongThucThanhPhan, i + 1, 1) + "*" + getDataTable(tblCongThucThanhPhan, i + 1, 2);
                    i++;
                }
                if (i == rowCounts - 1) {
                    congThuc += congThucThanhPhan;
                    i++;

                } else {
                    congThuc += congThucThanhPhan + ",";
                    congThuc += getDataTable(tblCongThucThanhPhan, i + 1, 1) + "*" + getDataTable(tblCongThucThanhPhan, i + 1, 2);
                    congThucThanhPhan = "";
                    i++;
                }
            }
            congThuc = "MIN(" + congThuc + ")";
        }
        txtCongThuc.setText(congThuc);
    }//GEN-LAST:event_btnTaoCongThucActionPerformed

    private void txtCongThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCongThucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCongThucActionPerformed

    public String getDataTable(JTable table, int row_index, int col_index) {
        return (String) table.getModel().getValueAt(row_index, col_index);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCongThuc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCongThuc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCongThuc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCongThuc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCongThuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuCongThuc;
    private javax.swing.JButton btnTaoCongThuc;
    private javax.swing.JComboBox<String> cbxLoaiCongThuc;
    private javax.swing.JComboBox<String> cbxTenCongThuc;
    private javax.swing.JComboBox<String> cbxTieuChi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spSoThanhPhanCon;
    public javax.swing.JTable tblCongThucThanhPhan;
    private javax.swing.JTextField txtCongThuc;
    private javax.swing.JTextField txtMaCongThuc;
    private javax.swing.JTextField txtMaMayIn;
    // End of variables declaration//GEN-END:variables
}
